-- MySQL Script generated by MySQL Workbench
-- Fri Jun  6 12:05:35 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema grow apphidro
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `grow apphidro` ;

-- -----------------------------------------------------
-- Schema grow apphidro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `grow apphidro` DEFAULT CHARACTER SET utf8 ;
USE `grow apphidro` ;

-- -----------------------------------------------------
-- Table `grow apphidro`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grow apphidro`.`roles` (
  `idroles` INT NOT NULL,
  `desripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idroles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grow apphidro`.`tipo documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grow apphidro`.`tipo documento` (
  `idtipo documento` INT NOT NULL,
  `tipo documentocol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idtipo documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grow apphidro`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grow apphidro`.`usuario` (
  `idusuario` INT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `idtipo documento` INT NOT NULL,
  `n_documento` VARCHAR(25) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(25) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  `roles_idroles` INT NOT NULL,
  `contraseñaNE` VARCHAR(45) NULL,
  `area` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`),
  CONSTRAINT `fk_usuario_roles1`
    FOREIGN KEY (`roles_idroles`)
    REFERENCES `grow apphidro`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_tipo documento1`
    FOREIGN KEY (`idtipo documento`)
    REFERENCES `grow apphidro`.`tipo documento` (`idtipo documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




CREATE INDEX `fk_usuario_genero1_idx` ON `grow apphidro`.`usuario` (`genero` ASC) ;

CREATE INDEX `fk_usuario_roles1_idx` ON `grow apphidro`.`usuario` (`roles_idroles` ASC) ;

CREATE INDEX `fk_usuario_tipo documento1_idx` ON `grow apphidro`.`usuario` (`idtipo documento` ASC) ;

CREATE INDEX `fk_usuario_roles1` ON `grow apphidro`.`usuario` (`roles_idroles` ASC) ;

CREATE INDEX `fk_usuario_tipo documento1` ON `grow apphidro`.`usuario` (`idtipo documento` ASC) ;



CREATE TABLE IF NOT EXISTS `grow apphidro`.`cultivo` (
  `idcultivo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  `fechaDeSiembra` DATE NOT NULL,
  `cultivocol` VARCHAR(45) NOT NULL,
  `especie` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idcultivo`))
ENGINE = InnoDB;

INSERT INTO `cultivo` (`idcultivo`, `nombre`, `cantidad`, `fechaDeSiembra`, `cultivocol`, `especie`) VALUES ('1', 'fresa', '10', '2025-07-07', 'cultivo prueba', '1-fruta')


CREATE TABLE IF NOT EXISTS `grow apphidro`.`notas` (
  `idnotas` INT NOT NULL AUTO_INCREMENT,
  `etiqueta` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `decripcion` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`idnotas`))
ENGINE = InnoDB;

INSERT INTO `notas` (`idnotas`, `etiqueta`, `nombre`, `decripcion`) VALUES ('1', 'importante', 'nota 1', 'nota de ejemplo')

-- -----------------------------------------------------
-- Table `grow apphidro`.`usuario_y_cultivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grow apphidro`.`usuario_y_cultivo` (
  `usuario_idusuario` INT NOT NULL,
  `nombre_culti` VARCHAR(45) NULL,
  CONSTRAINT `fk_usuario_has_cultivo_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `grow apphidro`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_has_cultivo_usuario1_idx` ON `grow apphidro`.`usuario_y_cultivo` (`usuario_idusuario` ASC) ;


-- -----------------------------------------------------
-- Table `grow apphidro`.`usuario_y_notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grow apphidro`.`usuario_y_notas` (
  `usuario_idusuario` INT NOT NULL,
  `notas_idnotas` INT NOT NULL,
  PRIMARY KEY (`usuario_idusuario`, `notas_idnotas`),
  CONSTRAINT `fk_usuario_has_notas_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `grow apphidro`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_notas_notas1`
    FOREIGN KEY (`notas_idnotas`)
    REFERENCES `grow apphidro`.`notas` (`idnotas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_has_notas_notas1_idx` ON `grow apphidro`.`usuario_y_notas` (`notas_idnotas` ASC) ;

CREATE INDEX `fk_usuario_has_notas_usuario1_idx` ON `grow apphidro`.`usuario_y_notas` (`usuario_idusuario` ASC) ;

CREATE INDEX `fk_usuario_has_notas_notas1` ON `grow apphidro`.`usuario_y_notas` (`notas_idnotas` ASC) ;


-- -----------------------------------------------------
-- Table `grow apphidro`.`especie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grow apphidro`.`especie` (
  `idespecie` INT NOT NULL AUTO_INCREMENT,
  `especie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idespecie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grow apphidro`.`usuario_y_especie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grow apphidro`.`usuario_y_especie` (
  `idusuario` INT NOT NULL,
  `especie` VARCHAR(45) NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
